name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install numpy
      - run: sudo apt update
      - run: sudo apt install inotify-tools
      - run: inotifywait -mr /home/runner/work/neo4j-apoc-procedures/neo4j-apoc-procedures/ --format '%T;%w;%f;%e' --timefmt %T -o /home/runner/inotify-logs.csv & echo 'basak'
      - run: touch starting_build_uses13_13
      - run: rm starting_build_uses13_13
      - uses: actions/checkout@v2
      - run: touch starting_build_SetupJDK11_14
      - run: rm starting_build_SetupJDK11_14
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - run: touch starting_build_uses19_19
      - run: rm starting_build_uses19_19
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      - run: touch starting_build_Grantexecutepermissionforgradlew_25
      - run: rm starting_build_Grantexecutepermissionforgradlew_25
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - run: touch starting_build_BuildwithGradle_27
      - run: rm starting_build_BuildwithGradle_27
      - name: Build with Gradle
        run: ./gradlew build
      - run: touch starting_build_Checkproceduresincludedinapocfull_29
      - run: rm starting_build_Checkproceduresincludedinapocfull_29
      - name: Check procedures included in apoc full
        run: git diff --exit-code full/src/main/resources/extended.txt || (echo "extended.txt file does not contain all changes" && exit -1)
      - run: touch starting_build_Archivetestresults_31
      - run: rm starting_build_Archivetestresults_31
      - name: Archive test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: |
            core/build/reports/tests/test/
            full/build/reports/tests/test/
            processor/build/reports/tests/test/
            test-startup/build/reports/tests/test/
            test-utils/build/reports/tests/test/
      - run: touch starting_finished_finished_8979874
        if: always()
      - run: rm starting_finished_finished_8979874
        if: always()
      - name: Execute py script # run file
        if: always()
        run: |
          python .github/workflows/script.py
      - run: cp /home/runner/inotify-logs.csv /home/runner/work/neo4j-apoc-procedures/neo4j-apoc-procedures/optimizing-ci-builds-ci-analysis/
        if: always()
      - name: Pushes analysis to another repository
        if: always()
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'optimizing-ci-builds-ci-analysis'
          destination-github-username: 'optimizing-ci-builds'
          destination-repository-name: 'ci-analyzes'
          target-branch: 'neo4j-apoc-procedures.1670424990'
          target-directory: 'neo4j-apoc-procedures/1670424990/.github/workflows/auto-cherry-pick/build'

